server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ff?characterEncoding=utf-8
    username: root
    password: root

  rabbitmq:
      addresses: 192.168.1.1:5672
      username: username
      password: password
      publisher-confirms: true
      virtual-host: /

#mybatis配置
mybatis:
  typeAliasesPackage: cn.fk.te.entity
  mapperLocations: classpath:mappers/*.xml


#当当定时任务
regCenter:
  serverList: localhost:2181
  namespace: elastic-job-lite-springboot
stockJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 2
  shardingItemParameters: 0=Chengdu0,1=Chengdu1