
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.199.225.159:3306/HH?characterEncoding=utf-8
    username: akai
    password: 123456

  rabbitmq:
      addresses: 192.168.1.1:5672
      username: username
      password: password
      publisher-confirms: true
      virtual-host: /

#mybatis配置
mybatis:
  typeAliasesPackage: cn.fk.te.entity
  mapperLocations: classpath:mappers/*.xml

#  https://www.cnblogs.com/xingzc/p/6029483.html事务