server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ff?characterEncoding=utf-8
    username: root
    password: root

  rabbitmq:
      addresses: 192.168.1.1:5672
      username: username
      password: password
      publisher-confirms: true
      virtual-host: /

#mybatis配置
mybatis:
  typeAliasesPackage: cn.fk.te.entity
  mapperLocations: classpath:mappers/*.xml

